# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurante_db
spring.datasource.username=postgres
spring.datasource.password=Jfrc11$$

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080

# Inicialización de datos (opcional)
spring.sql.init.mode=always

spring.security.user.name=admin
spring.security.user.password=1234

# JWT Configuration (agregar estas líneas)
app.jwt.secret=TuClaveSecretaMuySeguraParaProduccion2024RefugioBar
app.jwt.expiration=86400000